import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faAsterisk,
  faBatteryEmpty,
  faBatteryFull,
  faBatteryHalf,
  faBatteryQuarter,
  faBatteryThreeQuarters,
  faCaretDown,
  faCaretUp,
  faCheckCircle,
  faCog,
  faDownload,
  faExclamationTriangle,
  faMicrochip,
  faMusic,
  faPlay,
  faPowerOff,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faStar,
  faTimes,
  faTrash,
  faUsers,
  faVideo,
  faWrench
} from '@fortawesome/free-solid-svg-icons';
import {
  faCalendar,
  faCaretSquareDown,
  faCaretSquareLeft,
  faCaretSquareRight,
  faCaretSquareUp,
  faClock,
  faFile,
  faFileAudio,
  faFileVideo,
  faUserCircle,
  faWindowClose
} from '@fortawesome/free-regular-svg-icons';

// https://www.npmjs.com/package/@fortawesome/vue-fontawesome
library.add(
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faAsterisk,
  faBatteryEmpty,
  faBatteryFull,
  faBatteryHalf,
  faBatteryQuarter,
  faBatteryThreeQuarters,
  faCalendar,
  faCaretDown,
  faCaretSquareDown,
  faCaretSquareLeft,
  faCaretSquareRight,
  faCaretSquareUp,
  faCaretUp,
  faCheckCircle,
  faClock,
  faCog,
  faDownload,
  faExclamationTriangle,
  faFile,
  faFileAudio,
  faFileVideo,
  faMicrochip,
  faMusic,
  faPlay,
  faPowerOff,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faStar,
  faTimes,
  faTrash,
  faUserCircle,
  faUsers,
  faVideo,
  faWindowClose,
  faWrench
);

export default FontAwesomeIcon;
