import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faBatteryFull,
  faBatteryThreeQuarters,
  faBatteryHalf,
  faBatteryQuarter,
  faBatteryEmpty,
  faCog,
  faTrash,
  faVideo,
  faMusic,
  faCheckCircle,
  faAngleLeft,
  faAngleDoubleLeft,
  faAngleRight,
  faAngleDoubleRight,
  faAngleUp,
  faAngleDown,
  faCaretDown,
  faCaretUp,
  faQuestion,
  faAsterisk,
  faExclamationTriangle,
  faWrench,
  faUsers,
  faMicrochip,
  faPowerOff,
  faSearch,
  faTimes,
  faPlay
} from '@fortawesome/free-solid-svg-icons';
import {
  faCaretSquareDown,
  faCaretSquareLeft,
  faCaretSquareRight,
  faCaretSquareUp,
  faWindowClose,
  faUserCircle,
  faCalendar,
  faClock,
  faFileVideo,
  faFileAudio,
} from '@fortawesome/free-regular-svg-icons';

// https://www.npmjs.com/package/@fortawesome/vue-fontawesome
library.add(
  faTrash,
  faCaretSquareDown,
  faCaretSquareUp,
  faCaretSquareRight,
  faCaretSquareLeft,
  faCaretDown,
  faCaretUp,
  faWindowClose,
  faCog,
  faBatteryFull,
  faBatteryThreeQuarters,
  faBatteryHalf,
  faBatteryQuarter,
  faBatteryEmpty,
  faVideo,
  faMusic,
  faCheckCircle,
  faAngleLeft,
  faAngleDoubleLeft,
  faAngleRight,
  faAngleDoubleRight,
  faAngleUp,
  faAngleDown,
  faQuestion,
  faAsterisk,
  faExclamationTriangle,
  faWrench,
  faUsers,
  faMicrochip,
  faUserCircle,
  faPowerOff,
  faClock,
  faCalendar,
  faFileVideo,
  faFileAudio,
  faSearch,
  faTimes,
  faPlay
);

export default FontAwesomeIcon;
